//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import Rswift
import UIKit

/// This `R` struct is generated and contains references to static resources.
struct R: Rswift.Validatable {
  fileprivate static let applicationLocale = hostingBundle.preferredLocalizations.first.flatMap(Locale.init) ?? Locale.current
  fileprivate static let hostingBundle = Bundle(for: R.Class.self)
  
  static func validate() throws {
    try intern.validate()
  }
  
  /// This `R.color` struct is generated, and contains static references to 0 colors.
  @available(tvOS 11.0, *)
  @available(iOS 11.0, *)
  struct color {
    fileprivate init() {}
  }
  
  /// This `R.file` struct is generated, and contains static references to 2 files.
  struct file {
    /// Resource file `LICENSE`.
    static let licensE = Rswift.FileResource(bundle: R.hostingBundle, name: "LICENSE", pathExtension: "")
    /// Resource file `MainVCSettings.json`.
    static let mainVCSettingsJson = Rswift.FileResource(bundle: R.hostingBundle, name: "MainVCSettings", pathExtension: "json")
    
    /// `bundle.url(forResource: "LICENSE", withExtension: "")`
    static func licensE(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.licensE
      return fileResource.bundle.url(forResource: fileResource)
    }
    
    /// `bundle.url(forResource: "MainVCSettings", withExtension: "json")`
    static func mainVCSettingsJson(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.mainVCSettingsJson
      return fileResource.bundle.url(forResource: fileResource)
    }
    
    fileprivate init() {}
  }
  
  /// This `R.font` struct is generated, and contains static references to 0 fonts.
  struct font {
    fileprivate init() {}
  }
  
  /// This `R.image` struct is generated, and contains static references to 65 images.
  struct image {
    /// Image `LaunchImage`.
    static let launchImage = Rswift.ImageResource(bundle: R.hostingBundle, name: "LaunchImage")
    /// Image `avatar_default_big`.
    static let avatar_default_big = Rswift.ImageResource(bundle: R.hostingBundle, name: "avatar_default_big")
    /// Image `avatar_default_small`.
    static let avatar_default_small = Rswift.ImageResource(bundle: R.hostingBundle, name: "avatar_default_small")
    /// Image `avatar_default`.
    static let avatar_default = Rswift.ImageResource(bundle: R.hostingBundle, name: "avatar_default")
    /// Image `avatar_enterprise_vip`.
    static let avatar_enterprise_vip = Rswift.ImageResource(bundle: R.hostingBundle, name: "avatar_enterprise_vip")
    /// Image `avatar_grassroot`.
    static let avatar_grassroot = Rswift.ImageResource(bundle: R.hostingBundle, name: "avatar_grassroot")
    /// Image `avatar_vgirl`.
    static let avatar_vgirl = Rswift.ImageResource(bundle: R.hostingBundle, name: "avatar_vgirl")
    /// Image `avatar_vip`.
    static let avatar_vip = Rswift.ImageResource(bundle: R.hostingBundle, name: "avatar_vip")
    /// Image `common_button_white_disable`.
    static let common_button_white_disable = Rswift.ImageResource(bundle: R.hostingBundle, name: "common_button_white_disable")
    /// Image `common_icon_membership_expired`.
    static let common_icon_membership_expired = Rswift.ImageResource(bundle: R.hostingBundle, name: "common_icon_membership_expired")
    /// Image `common_icon_membership_level1`.
    static let common_icon_membership_level1 = Rswift.ImageResource(bundle: R.hostingBundle, name: "common_icon_membership_level1")
    /// Image `common_icon_membership_level2`.
    static let common_icon_membership_level2 = Rswift.ImageResource(bundle: R.hostingBundle, name: "common_icon_membership_level2")
    /// Image `common_icon_membership_level3`.
    static let common_icon_membership_level3 = Rswift.ImageResource(bundle: R.hostingBundle, name: "common_icon_membership_level3")
    /// Image `common_icon_membership_level4`.
    static let common_icon_membership_level4 = Rswift.ImageResource(bundle: R.hostingBundle, name: "common_icon_membership_level4")
    /// Image `common_icon_membership_level5`.
    static let common_icon_membership_level5 = Rswift.ImageResource(bundle: R.hostingBundle, name: "common_icon_membership_level5")
    /// Image `common_icon_membership_level6`.
    static let common_icon_membership_level6 = Rswift.ImageResource(bundle: R.hostingBundle, name: "common_icon_membership_level6")
    /// Image `common_icon_membership`.
    static let common_icon_membership = Rswift.ImageResource(bundle: R.hostingBundle, name: "common_icon_membership")
    /// Image `navigationbar_arrow_down`.
    static let navigationbar_arrow_down = Rswift.ImageResource(bundle: R.hostingBundle, name: "navigationbar_arrow_down")
    /// Image `navigationbar_arrow_up`.
    static let navigationbar_arrow_up = Rswift.ImageResource(bundle: R.hostingBundle, name: "navigationbar_arrow_up")
    /// Image `navigationbar_friendattention_highlighted`.
    static let navigationbar_friendattention_highlighted = Rswift.ImageResource(bundle: R.hostingBundle, name: "navigationbar_friendattention_highlighted")
    /// Image `navigationbar_friendattention`.
    static let navigationbar_friendattention = Rswift.ImageResource(bundle: R.hostingBundle, name: "navigationbar_friendattention")
    /// Image `navigationbar_pop_highlighted`.
    static let navigationbar_pop_highlighted = Rswift.ImageResource(bundle: R.hostingBundle, name: "navigationbar_pop_highlighted")
    /// Image `navigationbar_pop`.
    static let navigationbar_pop = Rswift.ImageResource(bundle: R.hostingBundle, name: "navigationbar_pop")
    /// Image `popover_background_left`.
    static let popover_background_left = Rswift.ImageResource(bundle: R.hostingBundle, name: "popover_background_left")
    /// Image `popover_background_right`.
    static let popover_background_right = Rswift.ImageResource(bundle: R.hostingBundle, name: "popover_background_right")
    /// Image `popover_background`.
    static let popover_background = Rswift.ImageResource(bundle: R.hostingBundle, name: "popover_background")
    /// Image `qrcode_border`.
    static let qrcode_border = Rswift.ImageResource(bundle: R.hostingBundle, name: "qrcode_border")
    /// Image `qrcode_button_background`.
    static let qrcode_button_background = Rswift.ImageResource(bundle: R.hostingBundle, name: "qrcode_button_background")
    /// Image `qrcode_embeddedimage_shadow`.
    static let qrcode_embeddedimage_shadow = Rswift.ImageResource(bundle: R.hostingBundle, name: "qrcode_embeddedimage_shadow")
    /// Image `qrcode_navigationbar_background`.
    static let qrcode_navigationbar_background = Rswift.ImageResource(bundle: R.hostingBundle, name: "qrcode_navigationbar_background")
    /// Image `qrcode_scanline_barcode`.
    static let qrcode_scanline_barcode = Rswift.ImageResource(bundle: R.hostingBundle, name: "qrcode_scanline_barcode")
    /// Image `qrcode_scanline_qrcode`.
    static let qrcode_scanline_qrcode = Rswift.ImageResource(bundle: R.hostingBundle, name: "qrcode_scanline_qrcode")
    /// Image `qrcode_tabbar_background`.
    static let qrcode_tabbar_background = Rswift.ImageResource(bundle: R.hostingBundle, name: "qrcode_tabbar_background")
    /// Image `qrcode_tabbar_icon_barcode_highlighted`.
    static let qrcode_tabbar_icon_barcode_highlighted = Rswift.ImageResource(bundle: R.hostingBundle, name: "qrcode_tabbar_icon_barcode_highlighted")
    /// Image `qrcode_tabbar_icon_barcode`.
    static let qrcode_tabbar_icon_barcode = Rswift.ImageResource(bundle: R.hostingBundle, name: "qrcode_tabbar_icon_barcode")
    /// Image `qrcode_tabbar_icon_qrcode_highlighted`.
    static let qrcode_tabbar_icon_qrcode_highlighted = Rswift.ImageResource(bundle: R.hostingBundle, name: "qrcode_tabbar_icon_qrcode_highlighted")
    /// Image `qrcode_tabbar_icon_qrcode`.
    static let qrcode_tabbar_icon_qrcode = Rswift.ImageResource(bundle: R.hostingBundle, name: "qrcode_tabbar_icon_qrcode")
    /// Image `qrcode_tip_background`.
    static let qrcode_tip_background = Rswift.ImageResource(bundle: R.hostingBundle, name: "qrcode_tip_background")
    /// Image `tabbar_background`.
    static let tabbar_background = Rswift.ImageResource(bundle: R.hostingBundle, name: "tabbar_background")
    /// Image `tabbar_compose_button_highlighted`.
    static let tabbar_compose_button_highlighted = Rswift.ImageResource(bundle: R.hostingBundle, name: "tabbar_compose_button_highlighted")
    /// Image `tabbar_compose_button`.
    static let tabbar_compose_button = Rswift.ImageResource(bundle: R.hostingBundle, name: "tabbar_compose_button")
    /// Image `tabbar_compose_icon_add_highlighted`.
    static let tabbar_compose_icon_add_highlighted = Rswift.ImageResource(bundle: R.hostingBundle, name: "tabbar_compose_icon_add_highlighted")
    /// Image `tabbar_compose_icon_add`.
    static let tabbar_compose_icon_add = Rswift.ImageResource(bundle: R.hostingBundle, name: "tabbar_compose_icon_add")
    /// Image `tabbar_discover_highlighted`.
    static let tabbar_discover_highlighted = Rswift.ImageResource(bundle: R.hostingBundle, name: "tabbar_discover_highlighted")
    /// Image `tabbar_discover`.
    static let tabbar_discover = Rswift.ImageResource(bundle: R.hostingBundle, name: "tabbar_discover")
    /// Image `tabbar_home_highlighted`.
    static let tabbar_home_highlighted = Rswift.ImageResource(bundle: R.hostingBundle, name: "tabbar_home_highlighted")
    /// Image `tabbar_home`.
    static let tabbar_home = Rswift.ImageResource(bundle: R.hostingBundle, name: "tabbar_home")
    /// Image `tabbar_message_center_highlighted`.
    static let tabbar_message_center_highlighted = Rswift.ImageResource(bundle: R.hostingBundle, name: "tabbar_message_center_highlighted")
    /// Image `tabbar_message_center`.
    static let tabbar_message_center = Rswift.ImageResource(bundle: R.hostingBundle, name: "tabbar_message_center")
    /// Image `tabbar_profile_highlighted`.
    static let tabbar_profile_highlighted = Rswift.ImageResource(bundle: R.hostingBundle, name: "tabbar_profile_highlighted")
    /// Image `tabbar_profile`.
    static let tabbar_profile = Rswift.ImageResource(bundle: R.hostingBundle, name: "tabbar_profile")
    /// Image `timeline_card_bottom_background`.
    static let timeline_card_bottom_background = Rswift.ImageResource(bundle: R.hostingBundle, name: "timeline_card_bottom_background")
    /// Image `timeline_card_bottom_line_highlighted`.
    static let timeline_card_bottom_line_highlighted = Rswift.ImageResource(bundle: R.hostingBundle, name: "timeline_card_bottom_line_highlighted")
    /// Image `timeline_card_middle_background_highlighted`.
    static let timeline_card_middle_background_highlighted = Rswift.ImageResource(bundle: R.hostingBundle, name: "timeline_card_middle_background_highlighted")
    /// Image `timeline_card_middle_background`.
    static let timeline_card_middle_background = Rswift.ImageResource(bundle: R.hostingBundle, name: "timeline_card_middle_background")
    /// Image `timeline_icon_comment`.
    static let timeline_icon_comment = Rswift.ImageResource(bundle: R.hostingBundle, name: "timeline_icon_comment")
    /// Image `timeline_icon_like`.
    static let timeline_icon_like = Rswift.ImageResource(bundle: R.hostingBundle, name: "timeline_icon_like")
    /// Image `timeline_icon_retweet`.
    static let timeline_icon_retweet = Rswift.ImageResource(bundle: R.hostingBundle, name: "timeline_icon_retweet")
    /// Image `timeline_icon_unlike`.
    static let timeline_icon_unlike = Rswift.ImageResource(bundle: R.hostingBundle, name: "timeline_icon_unlike")
    /// Image `visitordiscover_feed_image_house`.
    static let visitordiscover_feed_image_house = Rswift.ImageResource(bundle: R.hostingBundle, name: "visitordiscover_feed_image_house")
    /// Image `visitordiscover_feed_image_smallicon`.
    static let visitordiscover_feed_image_smallicon = Rswift.ImageResource(bundle: R.hostingBundle, name: "visitordiscover_feed_image_smallicon")
    /// Image `visitordiscover_feed_mask_smallicon`.
    static let visitordiscover_feed_mask_smallicon = Rswift.ImageResource(bundle: R.hostingBundle, name: "visitordiscover_feed_mask_smallicon")
    /// Image `visitordiscover_image_message`.
    static let visitordiscover_image_message = Rswift.ImageResource(bundle: R.hostingBundle, name: "visitordiscover_image_message")
    /// Image `visitordiscover_image_profile`.
    static let visitordiscover_image_profile = Rswift.ImageResource(bundle: R.hostingBundle, name: "visitordiscover_image_profile")
    /// Image `visitordiscover_signup_logo`.
    static let visitordiscover_signup_logo = Rswift.ImageResource(bundle: R.hostingBundle, name: "visitordiscover_signup_logo")
    
    /// `UIImage(named: "LaunchImage", bundle: ..., traitCollection: ...)`
    static func launchImage(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.launchImage, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "avatar_default", bundle: ..., traitCollection: ...)`
    static func avatar_default(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.avatar_default, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "avatar_default_big", bundle: ..., traitCollection: ...)`
    static func avatar_default_big(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.avatar_default_big, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "avatar_default_small", bundle: ..., traitCollection: ...)`
    static func avatar_default_small(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.avatar_default_small, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "avatar_enterprise_vip", bundle: ..., traitCollection: ...)`
    static func avatar_enterprise_vip(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.avatar_enterprise_vip, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "avatar_grassroot", bundle: ..., traitCollection: ...)`
    static func avatar_grassroot(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.avatar_grassroot, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "avatar_vgirl", bundle: ..., traitCollection: ...)`
    static func avatar_vgirl(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.avatar_vgirl, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "avatar_vip", bundle: ..., traitCollection: ...)`
    static func avatar_vip(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.avatar_vip, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "common_button_white_disable", bundle: ..., traitCollection: ...)`
    static func common_button_white_disable(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.common_button_white_disable, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "common_icon_membership", bundle: ..., traitCollection: ...)`
    static func common_icon_membership(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.common_icon_membership, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "common_icon_membership_expired", bundle: ..., traitCollection: ...)`
    static func common_icon_membership_expired(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.common_icon_membership_expired, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "common_icon_membership_level1", bundle: ..., traitCollection: ...)`
    static func common_icon_membership_level1(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.common_icon_membership_level1, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "common_icon_membership_level2", bundle: ..., traitCollection: ...)`
    static func common_icon_membership_level2(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.common_icon_membership_level2, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "common_icon_membership_level3", bundle: ..., traitCollection: ...)`
    static func common_icon_membership_level3(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.common_icon_membership_level3, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "common_icon_membership_level4", bundle: ..., traitCollection: ...)`
    static func common_icon_membership_level4(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.common_icon_membership_level4, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "common_icon_membership_level5", bundle: ..., traitCollection: ...)`
    static func common_icon_membership_level5(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.common_icon_membership_level5, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "common_icon_membership_level6", bundle: ..., traitCollection: ...)`
    static func common_icon_membership_level6(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.common_icon_membership_level6, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "navigationbar_arrow_down", bundle: ..., traitCollection: ...)`
    static func navigationbar_arrow_down(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.navigationbar_arrow_down, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "navigationbar_arrow_up", bundle: ..., traitCollection: ...)`
    static func navigationbar_arrow_up(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.navigationbar_arrow_up, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "navigationbar_friendattention", bundle: ..., traitCollection: ...)`
    static func navigationbar_friendattention(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.navigationbar_friendattention, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "navigationbar_friendattention_highlighted", bundle: ..., traitCollection: ...)`
    static func navigationbar_friendattention_highlighted(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.navigationbar_friendattention_highlighted, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "navigationbar_pop", bundle: ..., traitCollection: ...)`
    static func navigationbar_pop(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.navigationbar_pop, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "navigationbar_pop_highlighted", bundle: ..., traitCollection: ...)`
    static func navigationbar_pop_highlighted(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.navigationbar_pop_highlighted, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "popover_background", bundle: ..., traitCollection: ...)`
    static func popover_background(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.popover_background, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "popover_background_left", bundle: ..., traitCollection: ...)`
    static func popover_background_left(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.popover_background_left, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "popover_background_right", bundle: ..., traitCollection: ...)`
    static func popover_background_right(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.popover_background_right, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "qrcode_border", bundle: ..., traitCollection: ...)`
    static func qrcode_border(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.qrcode_border, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "qrcode_button_background", bundle: ..., traitCollection: ...)`
    static func qrcode_button_background(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.qrcode_button_background, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "qrcode_embeddedimage_shadow", bundle: ..., traitCollection: ...)`
    static func qrcode_embeddedimage_shadow(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.qrcode_embeddedimage_shadow, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "qrcode_navigationbar_background", bundle: ..., traitCollection: ...)`
    static func qrcode_navigationbar_background(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.qrcode_navigationbar_background, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "qrcode_scanline_barcode", bundle: ..., traitCollection: ...)`
    static func qrcode_scanline_barcode(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.qrcode_scanline_barcode, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "qrcode_scanline_qrcode", bundle: ..., traitCollection: ...)`
    static func qrcode_scanline_qrcode(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.qrcode_scanline_qrcode, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "qrcode_tabbar_background", bundle: ..., traitCollection: ...)`
    static func qrcode_tabbar_background(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.qrcode_tabbar_background, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "qrcode_tabbar_icon_barcode", bundle: ..., traitCollection: ...)`
    static func qrcode_tabbar_icon_barcode(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.qrcode_tabbar_icon_barcode, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "qrcode_tabbar_icon_barcode_highlighted", bundle: ..., traitCollection: ...)`
    static func qrcode_tabbar_icon_barcode_highlighted(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.qrcode_tabbar_icon_barcode_highlighted, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "qrcode_tabbar_icon_qrcode", bundle: ..., traitCollection: ...)`
    static func qrcode_tabbar_icon_qrcode(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.qrcode_tabbar_icon_qrcode, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "qrcode_tabbar_icon_qrcode_highlighted", bundle: ..., traitCollection: ...)`
    static func qrcode_tabbar_icon_qrcode_highlighted(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.qrcode_tabbar_icon_qrcode_highlighted, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "qrcode_tip_background", bundle: ..., traitCollection: ...)`
    static func qrcode_tip_background(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.qrcode_tip_background, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "tabbar_background", bundle: ..., traitCollection: ...)`
    static func tabbar_background(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.tabbar_background, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "tabbar_compose_button", bundle: ..., traitCollection: ...)`
    static func tabbar_compose_button(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.tabbar_compose_button, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "tabbar_compose_button_highlighted", bundle: ..., traitCollection: ...)`
    static func tabbar_compose_button_highlighted(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.tabbar_compose_button_highlighted, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "tabbar_compose_icon_add", bundle: ..., traitCollection: ...)`
    static func tabbar_compose_icon_add(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.tabbar_compose_icon_add, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "tabbar_compose_icon_add_highlighted", bundle: ..., traitCollection: ...)`
    static func tabbar_compose_icon_add_highlighted(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.tabbar_compose_icon_add_highlighted, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "tabbar_discover", bundle: ..., traitCollection: ...)`
    static func tabbar_discover(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.tabbar_discover, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "tabbar_discover_highlighted", bundle: ..., traitCollection: ...)`
    static func tabbar_discover_highlighted(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.tabbar_discover_highlighted, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "tabbar_home", bundle: ..., traitCollection: ...)`
    static func tabbar_home(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.tabbar_home, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "tabbar_home_highlighted", bundle: ..., traitCollection: ...)`
    static func tabbar_home_highlighted(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.tabbar_home_highlighted, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "tabbar_message_center", bundle: ..., traitCollection: ...)`
    static func tabbar_message_center(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.tabbar_message_center, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "tabbar_message_center_highlighted", bundle: ..., traitCollection: ...)`
    static func tabbar_message_center_highlighted(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.tabbar_message_center_highlighted, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "tabbar_profile", bundle: ..., traitCollection: ...)`
    static func tabbar_profile(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.tabbar_profile, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "tabbar_profile_highlighted", bundle: ..., traitCollection: ...)`
    static func tabbar_profile_highlighted(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.tabbar_profile_highlighted, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "timeline_card_bottom_background", bundle: ..., traitCollection: ...)`
    static func timeline_card_bottom_background(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.timeline_card_bottom_background, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "timeline_card_bottom_line_highlighted", bundle: ..., traitCollection: ...)`
    static func timeline_card_bottom_line_highlighted(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.timeline_card_bottom_line_highlighted, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "timeline_card_middle_background", bundle: ..., traitCollection: ...)`
    static func timeline_card_middle_background(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.timeline_card_middle_background, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "timeline_card_middle_background_highlighted", bundle: ..., traitCollection: ...)`
    static func timeline_card_middle_background_highlighted(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.timeline_card_middle_background_highlighted, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "timeline_icon_comment", bundle: ..., traitCollection: ...)`
    static func timeline_icon_comment(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.timeline_icon_comment, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "timeline_icon_like", bundle: ..., traitCollection: ...)`
    static func timeline_icon_like(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.timeline_icon_like, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "timeline_icon_retweet", bundle: ..., traitCollection: ...)`
    static func timeline_icon_retweet(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.timeline_icon_retweet, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "timeline_icon_unlike", bundle: ..., traitCollection: ...)`
    static func timeline_icon_unlike(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.timeline_icon_unlike, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "visitordiscover_feed_image_house", bundle: ..., traitCollection: ...)`
    static func visitordiscover_feed_image_house(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.visitordiscover_feed_image_house, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "visitordiscover_feed_image_smallicon", bundle: ..., traitCollection: ...)`
    static func visitordiscover_feed_image_smallicon(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.visitordiscover_feed_image_smallicon, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "visitordiscover_feed_mask_smallicon", bundle: ..., traitCollection: ...)`
    static func visitordiscover_feed_mask_smallicon(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.visitordiscover_feed_mask_smallicon, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "visitordiscover_image_message", bundle: ..., traitCollection: ...)`
    static func visitordiscover_image_message(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.visitordiscover_image_message, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "visitordiscover_image_profile", bundle: ..., traitCollection: ...)`
    static func visitordiscover_image_profile(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.visitordiscover_image_profile, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "visitordiscover_signup_logo", bundle: ..., traitCollection: ...)`
    static func visitordiscover_signup_logo(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.visitordiscover_signup_logo, compatibleWith: traitCollection)
    }
    
    fileprivate init() {}
  }
  
  /// This `R.nib` struct is generated, and contains static references to 1 nibs.
  struct nib {
    /// Nib `VisiterView`.
    static let visiterView = _R.nib._VisiterView()
    
    /// `UINib(name: "VisiterView", in: bundle)`
    static func visiterView(_: Void = ()) -> UIKit.UINib {
      return UIKit.UINib(resource: R.nib.visiterView)
    }
    
    fileprivate init() {}
  }
  
  /// This `R.reuseIdentifier` struct is generated, and contains static references to 1 reuse identifiers.
  struct reuseIdentifier {
    /// Reuse identifier `Home_StatusCell`.
    static let home_StatusCell: Rswift.ReuseIdentifier<Home_StatusCell> = Rswift.ReuseIdentifier(identifier: "Home_StatusCell")
    
    fileprivate init() {}
  }
  
  /// This `R.segue` struct is generated, and contains static references to 0 view controllers.
  struct segue {
    fileprivate init() {}
  }
  
  /// This `R.storyboard` struct is generated, and contains static references to 8 storyboards.
  struct storyboard {
    /// Storyboard `Discorver`.
    static let discorver = _R.storyboard.discorver()
    /// Storyboard `Main`.
    static let main = _R.storyboard.main()
    /// Storyboard `Messager`.
    static let messager = _R.storyboard.messager()
    /// Storyboard `Null`.
    static let null = _R.storyboard.null()
    /// Storyboard `Ouath`.
    static let ouath = _R.storyboard.ouath()
    /// Storyboard `PopView`.
    static let popView = _R.storyboard.popView()
    /// Storyboard `Profile`.
    static let profile = _R.storyboard.profile()
    /// Storyboard `home`.
    static let home = _R.storyboard.home()
    
    /// `UIStoryboard(name: "Discorver", bundle: ...)`
    static func discorver(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.discorver)
    }
    
    /// `UIStoryboard(name: "Main", bundle: ...)`
    static func main(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.main)
    }
    
    /// `UIStoryboard(name: "Messager", bundle: ...)`
    static func messager(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.messager)
    }
    
    /// `UIStoryboard(name: "Null", bundle: ...)`
    static func null(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.null)
    }
    
    /// `UIStoryboard(name: "Ouath", bundle: ...)`
    static func ouath(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.ouath)
    }
    
    /// `UIStoryboard(name: "PopView", bundle: ...)`
    static func popView(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.popView)
    }
    
    /// `UIStoryboard(name: "Profile", bundle: ...)`
    static func profile(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.profile)
    }
    
    /// `UIStoryboard(name: "home", bundle: ...)`
    static func home(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.home)
    }
    
    fileprivate init() {}
  }
  
  /// This `R.string` struct is generated, and contains static references to 0 localization tables.
  struct string {
    fileprivate init() {}
  }
  
  fileprivate struct intern: Rswift.Validatable {
    fileprivate static func validate() throws {
      try _R.validate()
    }
    
    fileprivate init() {}
  }
  
  fileprivate class Class {}
  
  fileprivate init() {}
}

struct _R: Rswift.Validatable {
  static func validate() throws {
    try storyboard.validate()
    try nib.validate()
  }
  
  struct nib: Rswift.Validatable {
    static func validate() throws {
      try _VisiterView.validate()
    }
    
    struct _VisiterView: Rswift.NibResourceType, Rswift.Validatable {
      let bundle = R.hostingBundle
      let name = "VisiterView"
      
      func firstView(owner ownerOrNil: AnyObject?, options optionsOrNil: [NSObject : AnyObject]? = nil) -> VisiterView? {
        return instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? VisiterView
      }
      
      static func validate() throws {
        if UIKit.UIImage(named: "common_button_white_disable", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'common_button_white_disable' is used in nib 'VisiterView', but couldn't be loaded.") }
        if UIKit.UIImage(named: "visitordiscover_feed_mask_smallicon", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'visitordiscover_feed_mask_smallicon' is used in nib 'VisiterView', but couldn't be loaded.") }
        if UIKit.UIImage(named: "visitordiscover_feed_image_smallicon", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'visitordiscover_feed_image_smallicon' is used in nib 'VisiterView', but couldn't be loaded.") }
        if UIKit.UIImage(named: "visitordiscover_feed_image_house", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'visitordiscover_feed_image_house' is used in nib 'VisiterView', but couldn't be loaded.") }
      }
      
      fileprivate init() {}
    }
    
    fileprivate init() {}
  }
  
  struct storyboard: Rswift.Validatable {
    static func validate() throws {
      try popView.validate()
      try discorver.validate()
      try messager.validate()
      try home.validate()
      try profile.validate()
    }
    
    struct discorver: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = UIKit.UINavigationController
      
      let bundle = R.hostingBundle
      let name = "Discorver"
      
      static func validate() throws {
        if UIKit.UIImage(named: "tabbar_discover") == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'tabbar_discover' is used in storyboard 'Discorver', but couldn't be loaded.") }
        if UIKit.UIImage(named: "tabbar_discover_highlighted") == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'tabbar_discover_highlighted' is used in storyboard 'Discorver', but couldn't be loaded.") }
      }
      
      fileprivate init() {}
    }
    
    struct home: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = UIKit.UINavigationController
      
      let bundle = R.hostingBundle
      let name = "home"
      
      static func validate() throws {
        if UIKit.UIImage(named: "timeline_icon_retweet") == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'timeline_icon_retweet' is used in storyboard 'home', but couldn't be loaded.") }
        if UIKit.UIImage(named: "timeline_card_middle_background_highlighted") == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'timeline_card_middle_background_highlighted' is used in storyboard 'home', but couldn't be loaded.") }
        if UIKit.UIImage(named: "common_icon_membership_expired") == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'common_icon_membership_expired' is used in storyboard 'home', but couldn't be loaded.") }
        if UIKit.UIImage(named: "tabbar_home") == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'tabbar_home' is used in storyboard 'home', but couldn't be loaded.") }
        if UIKit.UIImage(named: "avatar_enterprise_vip") == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'avatar_enterprise_vip' is used in storyboard 'home', but couldn't be loaded.") }
        if UIKit.UIImage(named: "timeline_icon_like") == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'timeline_icon_like' is used in storyboard 'home', but couldn't be loaded.") }
        if UIKit.UIImage(named: "timeline_icon_unlike") == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'timeline_icon_unlike' is used in storyboard 'home', but couldn't be loaded.") }
        if UIKit.UIImage(named: "timeline_icon_comment") == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'timeline_icon_comment' is used in storyboard 'home', but couldn't be loaded.") }
        if UIKit.UIImage(named: "tabbar_home_highlighted") == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'tabbar_home_highlighted' is used in storyboard 'home', but couldn't be loaded.") }
      }
      
      fileprivate init() {}
    }
    
    struct main: Rswift.StoryboardResourceWithInitialControllerType {
      typealias InitialController = MainTabBarViewController
      
      let bundle = R.hostingBundle
      let name = "Main"
      
      fileprivate init() {}
    }
    
    struct messager: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = UIKit.UINavigationController
      
      let bundle = R.hostingBundle
      let name = "Messager"
      
      static func validate() throws {
        if UIKit.UIImage(named: "tabbar_message_center") == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'tabbar_message_center' is used in storyboard 'Messager', but couldn't be loaded.") }
        if UIKit.UIImage(named: "tabbar_message_center_highlighted") == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'tabbar_message_center_highlighted' is used in storyboard 'Messager', but couldn't be loaded.") }
      }
      
      fileprivate init() {}
    }
    
    struct null: Rswift.StoryboardResourceWithInitialControllerType {
      typealias InitialController = UIKit.UITableViewController
      
      let bundle = R.hostingBundle
      let name = "Null"
      
      fileprivate init() {}
    }
    
    struct ouath: Rswift.StoryboardResourceWithInitialControllerType {
      typealias InitialController = WB_OuathViewController
      
      let bundle = R.hostingBundle
      let name = "Ouath"
      
      fileprivate init() {}
    }
    
    struct popView: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = PopView_ViewController
      
      let bundle = R.hostingBundle
      let name = "PopView"
      
      static func validate() throws {
        if UIKit.UIImage(named: "popover_background") == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'popover_background' is used in storyboard 'PopView', but couldn't be loaded.") }
      }
      
      fileprivate init() {}
    }
    
    struct profile: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = UIKit.UINavigationController
      
      let bundle = R.hostingBundle
      let name = "Profile"
      
      static func validate() throws {
        if UIKit.UIImage(named: "tabbar_profile") == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'tabbar_profile' is used in storyboard 'Profile', but couldn't be loaded.") }
        if UIKit.UIImage(named: "tabbar_profile_highlighted") == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'tabbar_profile_highlighted' is used in storyboard 'Profile', but couldn't be loaded.") }
      }
      
      fileprivate init() {}
    }
    
    fileprivate init() {}
  }
  
  fileprivate init() {}
}
